/**
 * This file was generated by GitHub Copilot (Claude 3.5 Sonnet)
 * Date: September 24, 2025
 */

/**
 * ESLint rule: import-order
 *
 * Проверяет правильный порядок импортов в файлах согласно правилам проекта:
 * 1. Приложение-образующие зависимости (react, redux, router)
 * 2. Функциональные зависимости внешние (keycloak, momentjs и пр.)
 * 3. BBR библиотеки (@bodynarf/utils, затем @bodynarf/react.components)
 * 4. Функциональные зависимости приложения (@app/auth/ и пр.)
 * 5. Модели и базовые значения (@app/models/, @app/shared/values)
 * 6. Общие элементы (@app/shared/)
 * 7. Утилиты (@app/utils)
 * 8. Корневые функции приложения (@app/core/)
 * 9. Элементы состояния (@app/store/)
 * 10. Хуки (@app/hooks)
 * 11. Ресурсы (@app/assets/)
 * 12. Файл стилей (./styles.scss)
 * 13. Файлы текущей директории (./file.ext)
 * 14. Файлы компонентов поддерева (../components/)
 *
 * Между группами должны быть пустые строки
 */

export default {
    meta: {
        type: "problem",
        docs: {
            description: "Enforce imports to be ordered according to project guidelines",
            category: "Stylistic Issues",
            recommended: false
        },
        fixable: null,
        schema: [],
        messages: {
            wrongImportOrder: "Import '{{importPath}}' ({{currentGroup}}) should come {{direction}} {{expectedGroup}} imports",
            missingEmptyLine: "Expected empty line between {{prevGroup}} and {{currentGroup}} import groups",
            extraEmptyLine: "Unexpected empty line within {{group}} import group"
        },
    },

    create(context) {
        // Группы импортов в порядке приоритета
        const IMPORT_GROUPS = {
            core: {
                order: 1,
                name: "core",
                displayName: "приложение-образующих",
                patterns: [
                    /^react($|\/)/,
                    /^redux($|\/)/,
                    /^redux-thunk($|\/)/,
                    /^react-redux($|\/)/,
                    /^react-router($|\/)/,
                    /^react-router-dom($|\/)/,
                    /^@reduxjs\/toolkit($|\/)/
                ]
            },
            functional: {
                order: 2,
                name: "functional",
                displayName: "функциональных зависимостей",
                patterns: [
                    /^keycloak/,
                    /^moment/,
                    /^axios/,
                    /^lodash/,
                    /^classnames/,
                    /^clsx/,
                    /^uuid/,
                    // Другие внешние библиотеки, не попадающие в core или bbr
                    // Исключаем @app/* импорты
                    /^(?!@app\/)[^.@]/
                ]
            },
            bbr: {
                order: 3,
                name: "bbr",
                displayName: "BBR библиотек",
                patterns: [
                    /^@bodynarf\/utils/,
                    /^@bodynarf\/react\.components/
                ],
                // Внутренний порядок в группе BBR
                internalOrder: [
                    { pattern: /^@bodynarf\/utils/, name: "utils" },
                    { pattern: /^@bodynarf\/react\.components/, name: "components" }
                ]
            },
            models: {
                order: 4,
                name: "models",
                displayName: "моделей и базовых значений",
                patterns: [
                    /^@app\/models($|\/)/,
                    /^@app\/shared\/values($|\/)/
                ],
                internalOrder: [
                    { pattern: /^@app\/models($|\/)/, name: "моделей приложения" },
                    { pattern: /^@app\/shared\/values($|\/)/, name: "общих значений" }
                ]
            },
            shared: {
                order: 5,
                name: "shared",
                displayName: "общих элементов",
                patterns: [
                    /^@app\/shared\/(?!values($|\/))/
                ]
            },
            utils: {
                order: 6,
                name: "utils",
                displayName: "утилит",
                patterns: [
                    /^@app\/utils/
                ]
            },
            core_app: {
                order: 7,
                name: "core_app",
                displayName: "корневых функций",
                patterns: [
                    /^@app\/core/
                ]
            },
            store: {
                order: 8,
                name: "store",
                displayName: "состояния",
                patterns: [
                    /^@app\/store/
                ]
            },
            hooks: {
                order: 9,
                name: "hooks",
                displayName: "хуков",
                patterns: [
                    /^@app\/hooks/
                ]
            },
            sharedComponents: {
                order: 9.5,
                name: "sharedComponents",
                displayName: "функциональных зависимостей",
                patterns: [
                    /^@app\/sharedComponents/
                ]
            },
            assets: {
                order: 10,
                name: "assets",
                displayName: "ресурсов",
                patterns: [
                    /^@app\/assets/
                ]
            },
            styles: {
                order: 11,
                name: "styles",
                displayName: "стилей",
                patterns: [
                    /^\.\/styles\.scss$/,
                    /^\.\/styles\.module\.scss$/,
                ]
            },
            current: {
                order: 12,
                name: "current",
                displayName: "файлов текущей директории",
                patterns: [
                    /^\.\/(?!styles\.scss$)[^\/]+$/,  // Файлы из текущей директории, кроме styles.scss
                    /^\.\/(?!styles\.module\.scss$)[^\/]+$/,  // Файлы из текущей директории, кроме styles.module.scss
                ]
            },
            components: {
                order: 13,
                name: "components",
                displayName: "компонентов поддерева",
                patterns: [
                    /^\.\.\/components\//,
                    /^\.\/components\//,
                    /^\.\.?\/.+/,  // Относительные импорты с подпапками
                    /^\.$/         // Импорт из текущей директории "."
                ]
            }
        };

        /**
         * Определяет группу импорта по его пути
         * @param {string} importPath - путь импорта
         * @returns {Object} группа импорта
         */
        function getImportGroup(importPath) {
            // Проверяем группы в порядке специфичности
            // Сначала более специфичные паттерны

            // React и связанные библиотеки
            if (IMPORT_GROUPS.core.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.core;
            }

            // Проверяем функциональные зависимости ПЕРЕД BBR, чтобы исключить @app/*
            if (IMPORT_GROUPS.functional.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.functional;
            }

            // BBR библиотеки
            if (IMPORT_GROUPS.bbr.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.bbr;
            }

            // Модели и значения - проверяем оба паттерна для одной группы
            if (IMPORT_GROUPS.models.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.models;
            }

            // Общие элементы (проверяем после models, чтобы не перехватить @app/shared/values)
            if (IMPORT_GROUPS.shared.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.shared;
            }

            // Утилиты
            if (IMPORT_GROUPS.utils.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.utils;
            }

            // Корневые функции
            if (IMPORT_GROUPS.core_app.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.core_app;
            }

            // Store
            if (IMPORT_GROUPS.store.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.store;
            }

            // Hooks
            if (IMPORT_GROUPS.hooks.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.hooks;
            }

            // SharedComponents
            if (IMPORT_GROUPS.sharedComponents.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.sharedComponents;
            }

            // Assets
            if (IMPORT_GROUPS.assets.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.assets;
            }

            // Стили
            if (IMPORT_GROUPS.styles.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.styles;
            }

            // Файлы текущей директории (проверяем перед компонентами)
            if (IMPORT_GROUPS.current.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.current;
            }

            // Компоненты
            if (IMPORT_GROUPS.components.patterns.some(pattern => pattern.test(importPath))) {
                return IMPORT_GROUPS.components;
            }

            // Если не найдено среди специфичных групп, может быть @app/auth/* или другие @app/* импорты
            // которые не попали в конкретные категории - относим к функциональным зависимостям  
            // но они должны идти после BBR из-за изменения порядка проверки выше
            if (importPath.startsWith('@app/auth/')) {
                // Создаем специальную группу для @app/auth после BBR
                return {
                    order: 3.5, // Между BBR (3) и models (4)
                    name: "app_auth",
                    displayName: "функциональных зависимостей"
                };
            }

            // Все остальное - функциональные зависимости
            return IMPORT_GROUPS.functional;
        }

        /**
         * Получает внутренний порядок импорта в группе
         * @param {Object} group - группа импорта
         * @param {string} importPath - путь импорта
         * @returns {number} порядок внутри группы или 0 если не найден
         */
        function getInternalOrder(group, importPath) {
            if (!group.internalOrder) return 0;

            for (let i = 0; i < group.internalOrder.length; i++) {
                if (group.internalOrder[i].pattern.test(importPath)) {
                    return i + 1;
                }
            }
            return 0;
        }

        /**
         * Проверяет, должны ли две группы быть разделены пустой строкой
         * @param {Object} lastGroup - предыдущая группа
         * @param {Object} currentGroup - текущая группа
         * @returns {boolean} true если нужна пустая строка
         */
        function shouldHaveEmptyLineBetween(lastGroup, currentGroup) {
            // Если это действительно разные группы
            if (lastGroup.name !== currentGroup.name) {
                return true;
            }

            // Если это одна и та же группа, пустая строка не нужна
            return false;
        }

        /**
         * Проверяет порядок импортов и пустые строки между группами
         * @param {Array} imports - массив импортов для проверки
         */
        function checkImportsOrder(imports) {
            if (imports.length <= 1) return;

            let lastGroup = null;
            let lastImportLine = null;
            let lastInternalOrder = null;

            for (let i = 0; i < imports.length; i++) {
                const currentImport = imports[i];
                const currentGroup = getImportGroup(currentImport.source);
                const currentLine = currentImport.line;
                const currentInternalOrder = getInternalOrder(currentGroup, currentImport.source);

                // Проверяем порядок групп
                if (lastGroup && currentGroup.order < lastGroup.order) {
                    context.report({
                        node: currentImport.node,
                        messageId: "wrongImportOrder",
                        data: {
                            importPath: currentImport.source,
                            currentGroup: currentGroup.displayName,
                            direction: "после",
                            expectedGroup: lastGroup.displayName
                        }
                    });
                }

                // Проверяем внутренний порядок в группе
                if (lastGroup &&
                    lastGroup.name === currentGroup.name &&
                    currentGroup.internalOrder &&
                    lastInternalOrder > 0 &&
                    currentInternalOrder > 0 &&
                    currentInternalOrder < lastInternalOrder) {

                    const expectedItem = currentGroup.internalOrder[lastInternalOrder - 1];
                    const currentItem = currentGroup.internalOrder[currentInternalOrder - 1];

                    context.report({
                        node: currentImport.node,
                        messageId: "wrongImportOrder",
                        data: {
                            importPath: currentImport.source,
                            currentGroup: currentGroup.displayName,
                            direction: "после",
                            expectedGroup: currentGroup.displayName
                        }
                    });
                }

                // Проверяем пустые строки между разными группами
                if (lastGroup && shouldHaveEmptyLineBetween(lastGroup, currentGroup)) {
                    const linesBetween = currentLine - lastImportLine - 1;

                    if (linesBetween === 0) {
                        context.report({
                            node: currentImport.node,
                            messageId: "missingEmptyLine",
                            data: {
                                prevGroup: lastGroup.displayName,
                                currentGroup: currentGroup.displayName
                            }
                        });
                    }
                }

                // Проверяем лишние пустые строки внутри одной группы
                if (lastGroup && lastGroup.name === currentGroup.name) {
                    const linesBetween = currentLine - lastImportLine - 1;

                    if (linesBetween > 0) {
                        context.report({
                            node: currentImport.node,
                            messageId: "extraEmptyLine",
                            data: {
                                group: currentGroup.displayName
                            }
                        });
                    }
                }

                lastGroup = currentGroup;
                lastImportLine = currentLine;
                lastInternalOrder = currentInternalOrder;
            }
        }

        /**
         * Собирает все импорты из программы
         * @param {Object} program - AST узел программы
         * @returns {Array} массив импортов
         */
        function collectImports(program) {
            const imports = [];

            for (const statement of program.body) {
                if (statement.type === "ImportDeclaration") {
                    imports.push({
                        node: statement,
                        source: statement.source.value,
                        line: statement.loc.start.line
                    });
                }
            }

            return imports;
        }

        return {
            Program(node) {
                const imports = collectImports(node);
                checkImportsOrder(imports);
            }
        };
    }
};
