/**
 * This file was generated by GitHub Copilot (Claude 3.5 Sonnet)
 * Date: September 24, 2025
 */

import jsxPropsPerLine from "./jsx-props-per-line.js";
import optionalPropsLast from "./optional-props-last.js";
import hooksOrder from "./hooks-order.js";
import importOrder from "./import-order.js";
import noCrossModuleImports from "./no-cross-module-imports.js";
import functionalComponentDefinition from "./functional-component-definition.js";
import noDuplicateImports from "./no-duplicate-imports.js";
import noSnakeCase from "./no-snake-case.js";
import componentPascalCase from "./component-pascal-case.js";
import propsCamelCase from "./props-camel-case.js";
import eslintDisableRequireReason from "./eslint-disable-require-reason.js";

export default {
	rules: {
		"jsx-props-per-line": jsxPropsPerLine,
		"optional-props-last": optionalPropsLast,
		"hooks-order": hooksOrder,
		"import-order": importOrder,
		"no-cross-module-imports": noCrossModuleImports,
		"functional-component-definition": functionalComponentDefinition,
		"no-duplicate-imports": noDuplicateImports,
		"no-snake-case": noSnakeCase,
		"component-pascal-case": componentPascalCase,
		"props-camel-case": propsCamelCase,
		"eslint-disable-require-reason": eslintDisableRequireReason,
	}
};
